### ISSUE TITLE
Add the concept of visibility to the workspace creation

### ISSUE THREAD

**Issue by swampie** [seqeralabs/tower-cli#105] opened 2021-11-11 14:26 UTC
Currently (https://github.com/seqeralabs/tower-cli/blob/master/src/main/java/io/seqera/tower/cli/commands/workspaces/CreateCmd.java) the workspace create command set the visibility to private.

Add a new option (visibility) which accepts PRIVATE or SHARED values and change the body accordingly: PRIVATE should be the default if the option is missing

**Comment by jordeu** [comment] 2022-01-25 13:18
Is this a duplicate of #76 ?

**Closed** 2022-04-13 14:32 UTC
