### ISSUE TITLE
Add binaries for macOS ARM ?

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/tower-cli#354] opened 2023-10-23 08:52 UTC
Hi team,

similar to what @pditommaso has done for [Wave-CLI](https://github.com/seqeralabs/wave-cli/releases/tag/v1.0.0), how about providing ARM macOS binaries for Tower-CLI as well? I can see better performance for Wave-CLI compared to the x86 build (emulated runtime).

**Comment by JaimeSeqLabs** [comment] 2023-10-26 13:51
Hi @marcodelapierre,

Absolutely, I've been experimenting a bit in branch https://github.com/seqeralabs/tower-cli/tree/apple-silicon-releases but there are some problems with the binary tests failing https://github.com/seqeralabs/tower-cli/actions/runs/6510391361/job/17683981215 .

I will investigate the issue, but other than that it is perfectly feasible.
I'll also link that branch to this issue for anyone to check the build.yml.

**Comment by marcodelapierre** [comment] 2023-10-26 15:08
Thanks for sharing this update @JaimeSeqLabs  :)

I see at [line 1122](https://github.com/seqeralabs/tower-cli/actions/runs/6510391361/job/17683981215#step:11:1123) that about half of the approx 700 binary tests failed - a large number - Sounds like it might be some fundamental / high-level modification that is required to have them .. just a gut feeling though at this stage.

Is there anything I can assist it with at this stage?

**Comment by JaimeSeqLabs** [comment] 2023-10-26 15:30
It would be really helpful to have the binary tests run on a M1/M2 machine, I don't have access to one myself.
Just to see if the tests run fine as they are or if we are missing something else in the GH action setup.

Following the build.yml file:
```
# Build native image
./gradlew nativeCompile

# Binary tests
export TOWER_CLI=build/native/nativeCompile
./gradlew cleanTest test
```

**Comment by pditommaso** [comment] 2023-10-26 15:38
Have you downloaded the logs? all tests fail like this 

```
org.opentest4j.AssertionFailedError: expected: <{
  "connectionCheck" : 1,
  "versionCheck" : 1,
  "credentialsCheck" : 1,
  "opts" : {
    "towerVersion" : "22.3.0-torricelli",
    "towerApiEndpoint" : "http://localhost:50404",
    "cliVersion" : "0.9.0 (37f01a3)",
    "cliApiVersion" : "1.15",
    "towerApiVersion" : "1.15.0",
    "userName" : "jordi"
  }
}> but was: <>
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at app//io.seqera.tower.cli.BaseCmdTest.assertOutput(BaseCmdTest.java:180)
	at app//io.seqera.tower.cli.InfoCmdTest.testInfo(InfoCmdTest.java:61)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)

```

**Comment by JaimeSeqLabs** [comment] 2023-10-26 15:46
Yes, it seems to be related to the reflection configuration.
The problem is that those tests are passing just fine on the rest of the platforms and I'm not sure if the reflection error is because of the GH action environment or because we are not properly configuring the project's build for M1/M2.

**Comment by JaimeSeqLabs** [comment] 2023-11-13 16:20
Oops, it was just a dumb typo, fixed in https://github.com/seqeralabs/tower-cli/commit/e6d08383dee64abf2d8e3bebdf5170d4da682f4e

**Closed** 2023-11-21 11:26 UTC
Labels: enhancement

**Comment by marcodelapierre** [comment] 2023-11-22 02:28
Thanks Jaime!
