### ISSUE TITLE
Add the headJobServiceAccountEmail to Google Batch Advanced Options

### ISSUE THREAD

**Issue by swampie** [seqeralabs/tower-cli#316] opened 2023-08-01 06:23 UTC
Add a new option to specify an email as the Head Job Service Account Email property in Google Batch Advanced Options

**Comment by tcrespog** [comment] 2024-08-08 10:14
Closing on GitHub. The issue is being tracked in Jira now: [PLAT-186](https://seqera.atlassian.net/browse/PLAT-186)

**Closed** 2024-09-11 07:51 UTC
