### ISSUE TITLE
help in the CLI is limited if the user is not authenticated

### ISSUE THREAD

**Issue by mribeirodantas** [seqeralabs/tower-cli#250] opened 2022-08-24 17:00 UTC
Both @ewels and I installed tower-cli yesterday but we were surprised to realize that our `--help` commands were outputting different results. We then noticed that Phil had already set up as an environment variable (I suppose) his access token and I hadn't. I can reproduce locally the issue by just installing `tw` and running it with a token and without one (I already deleted this token, so don't worry):

<img width="854" alt="Screen Shot 2022-08-24 at 13 57 53" src="https://user-images.githubusercontent.com/1023197/186478358-ed8f1057-b1fd-41f3-b88b-ba6fab55b7cb.png">
<img width="1135" alt="Screen Shot 2022-08-24 at 13 58 05" src="https://user-images.githubusercontent.com/1023197/186478372-3b7ff4aa-7430-4d31-9aab-8045c0b69294.png">

Is this done by design!? I would expect the `--help` to be as informative as possible to any user, including the one that hasn't configured it yet which is probably a new user 😅

**Comment by tcrespog** [comment] 2022-08-29 06:54
Duplicate of: https://github.com/seqeralabs/tower-cli/issues/228.

**Closed** 2022-08-29 08:57 UTC
Labels: bug, question
